# Generated by Django 3.2.18 on 2023-02-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('prompts', models.CharField(max_length=200, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
